# Generated by Django 3.0.3 on 2020-04-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_RSVP',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='guests_confirmed',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_RSVP',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='total_guests_confirmed',
            field=models.IntegerField(null=True),
        ),
    ]
