# Generated by Django 3.0.3 on 2020-04-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Invitados'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name_plural': 'Invitaciones'},
        ),
    ]
