# Generated by Django 3.0.3 on 2020-04-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpApp', '0002_auto_20200429_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_RSVP',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='guests_confirmed',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvpApp.Guest', verbose_name='Relacionar con invitado'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_RSVP',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='total_guests_confirmed',
            field=models.IntegerField(null=True),
        ),
    ]
