# Generated by Django 3.0.3 on 2020-05-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpApp', '0002_auto_20200429_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_RSVP',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='guests_confirmed',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_RSVP',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='total_guests_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
